# Generated by Django 4.2.7 on 2024-07-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='origen',
            new_name='inicio',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='conexion',
            unique_together={('ubicacion1', 'ubicacion2')},
        ),
    ]
